name: CI - Build, Unit Tests & Selenium Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Compose Build
      run: docker compose build
      working-directory: gestion-app

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Levantar base de datos y app
      run: docker compose up -d db nextapp
      working-directory: gestion-app

    - name: Esperar que la base de datos esté lista
      run: |
        for i in {1..10}; do
          if docker exec postgres_container pg_isready -U postgres; then
            echo "✅ Base de datos lista"
            break
          fi
          echo "⏳ Esperando base de datos... intento $i"
          sleep 5
        done

    - name: Ejecutar pruebas unitarias (dentro del contenedor nextapp)
      run: docker compose exec -T nextapp npm run test
      working-directory: gestion-app

    - name: Tear down
      if: always()
      run: docker compose down
      working-directory: gestion-app

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jera123
          POSTGRES_DB: soft-tech
        ports:
          - 5432:5432

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Levantar la app como contenedor (Next.js)
      run: docker compose up -d nextapp
      working-directory: gestion-app

    - name: Esperar que la aplicación esté levantada (Healthcheck real)
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:3004/ > /dev/null; then
            echo "✅ Aplicación levantada"
            break
          fi
          echo "⏳ Esperando... intento $i"
          sleep 5
        done

    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Ejecutar pruebas de Selenium - iniciar sesión
      run: python Pruebas_automatizadas/IniciarSesion.py

    - name: Ejecutar pruebas de Selenium - agregar docente
      run: python Pruebas_automatizadas/Prueba_AgregarDocente.py

    - name: Tear down
      if: always()
      run: docker compose down
      working-directory: gestion-app
