name: CI - Build, Unit Tests & Selenium Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: gestion-app/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('gestion-app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-

    - name: Docker Compose Build
      run: docker compose build > build.log 2>&1
      working-directory: gestion-app

    - name: Subir logs de build como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: logs-build
        path: gestion-app/build.log

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Levantar base de datos y app
      run: docker compose up -d db nextapp > up.log 2>&1
      working-directory: gestion-app

    - name: Esperar que la base de datos esté lista
      run: |
        for i in {1..10}; do
          if docker exec postgres_container pg_isready -U postgres; then
            echo "✅ Base de datos lista"
            break
          fi
          echo "⏳ Esperando base de datos... intento $i"
          sleep 5
        done > db_ready.log 2>&1
      working-directory: gestion-app

    - name: Ejecutar pruebas unitarias (dentro del contenedor nextapp)
      run: docker compose exec -T nextapp npm run test > unit-tests.log 2>&1
      working-directory: gestion-app

    - name: Tear down
      if: always()
      run: docker compose down > down.log 2>&1
      working-directory: gestion-app

    - name: Subir logs de unit tests como artefactos
      uses: actions/upload-artifact@v4
      with:
        name: logs-unit-tests
        path: |
          gestion-app/unit-tests.log
          gestion-app/up.log
          gestion-app/db_ready.log
          gestion-app/down.log

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: jera123
          POSTGRES_DB: soft-tech
        ports:
          - 5432:5432

      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Levantar la app como contenedor (Next.js)
      run: docker compose up -d nextapp > up_integration.log 2>&1
      working-directory: gestion-app

    - name: Esperar que la aplicación esté levantada (Healthcheck real)
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:3004/ > /dev/null; then
            echo "✅ Aplicación levantada"
            break
          fi
          echo "⏳ Esperando... intento $i"
          sleep 5
        done > app_ready.log 2>&1

    - name: Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager> pip_install.log 2>&1

    - name: Ejecutar pruebas de Selenium - iniciar sesión
      run: python Pruebas_automatizadas/IniciarSesion.py > selenium_login.log 2>&1

    - name: Ejecutar pruebas de Selenium - agregar docente
      run: python Pruebas_automatizadas/Prueba_AgregarDocente.py > selenium_add_teacher.log 2>&1

    - name: Tear down
      if: always()
      run: docker compose down > down_integration.log 2>&1
      working-directory: gestion-app

    - name: Subir logs de integración como artefactos
      uses: actions/upload-artifact@v4
      with:
        name: logs-integration-tests
        path: |
          gestion-app/up_integration.log
          gestion-app/app_ready.log
          gestion-app/pip_install.log
          gestion-app/selenium_login.log
          gestion-app/selenium_add_teacher.log
          gestion-app/down_integration.log
