name: CI - Build and Test with Selenium

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: docker compose version

    - name: Build and start containers
      run: docker compose up -d --build
      working-directory: gestion-app

    - name: Esperar que la aplicación esté arriba
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:3004/ > /dev/null; then
            echo "✅ Aplicación levantada"
            break
          fi
          echo "⏳ Esperando... intento $i"
          sleep 5
        done
      working-directory: gestion-app

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Selenium test - iniciar sesion
      run: python Pruebas_automatizadas\IniciarSesion.py

    - name: Run Selenium test - agregar docente
      run: python Pruebas_automatizadas/Prueba_AgregarDocente.py

    - name: Tear down containers
      if: always()
      run: docker compose down
      working-directory: gestion-app
