name: Run on Commit

on:
  push:
    branches:
      - main  # o la rama que uses, como 'master' o 'develop'

jobs:
  simple-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print commit message
        run: echo "Commit realizado. GitHub Actions ejecutado correctamente."
